--- #YAML:1.0
name:                FrameNet-QueryData
version:             0.04
abstract:            A module for accessing the FrameNet data. 
license:             ~
author:              
    - Nils Reiter <reiter@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Getopt::Long:                  2.34
    Test::More:                    0
    XML::TreeBuilder:              3.09
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
